import { Injectable } from '@angular/core';
import { WebAnalysisResult } from '../models/website.model';

@Injectable({
  providedIn: 'root'
})
export class ExportService {

  exportToMarkdown(result: WebAnalysisResult): void {
    const markdown = this.generateMarkdown(result);
    this.downloadFile(markdown, `web-analysis-${this.sanitizeFilename(result.siteName)}.md`, 'text/markdown');
  }

  exportToHtml(result: WebAnalysisResult): void {
    const html = this.generateHtml(result);
    this.downloadFile(html, `web-analysis-${this.sanitizeFilename(result.siteName)}.html`, 'text/html');
  }

  exportToCsv(result: WebAnalysisResult): void {
    const csv = this.generateCsv(result);
    this.downloadFile(csv, `web-analysis-${this.sanitizeFilename(result.siteName)}.csv`, 'text/csv');
  }

  exportToJson(result: WebAnalysisResult): void {
    const json = JSON.stringify(result, null, 2);
    this.downloadFile(json, `web-analysis-${this.sanitizeFilename(result.siteName)}.json`, 'application/json');
  }

  exportToGitHubIssues(result: WebAnalysisResult): void {
    const issues = this.generateGitHubIssues(result);
    this.downloadFile(issues, `github-issues-${this.sanitizeFilename(result.siteName)}.md`, 'text/markdown');
  }

  exportToJira(result: WebAnalysisResult): void {
    const jira = this.generateJiraFormat(result);
    this.downloadFile(jira, `jira-issues-${this.sanitizeFilename(result.siteName)}.txt`, 'text/plain');
  }

  generateBadgeUrl(result: WebAnalysisResult): string {
    const score = result.overallScore;
    let color = 'red';
    if (score >= 80) color = 'brightgreen';
    else if (score >= 60) color = 'yellow';
    else if (score >= 40) color = 'orange';
    
    return `https://img.shields.io/badge/Website_Quality-${score}%25-${color}?style=for-the-badge`;
  }

  private generateMarkdown(result: WebAnalysisResult): string {
    const date = new Date(result.analyzedAt).toLocaleString();
    
    let md = `# Website Analysis Report\n\n`;
    md += `## Site Information\n\n`;
    md += `- **Website:** ${result.siteName}\n`;
    md += `- **URL:** ${result.siteUrl}\n`;
    md += `- **Analyzed:** ${date}\n`;
    md += `- **Overall Score:** ${result.overallScore}/100\n\n`;
    
    md += `## Summary\n\n`;
    md += `| Metric | Count |\n`;
    md += `|--------|-------|\n`;
    md += `| Total Rules Checked | ${result.summary.totalRules} |\n`;
    md += `| Passed | ${result.summary.passedRules} |\n`;
    md += `| Failed | ${result.summary.failedRules} |\n`;
    md += `| Warnings | ${result.summary.warningRules} |\n\n`;
    
    if (result.violations && result.violations.length > 0) {
      md += `## Issues and Violations\n\n`;
      
      result.violations.forEach((v, i) => {
        md += `### ${i + 1}. ${v.ruleName}\n\n`;
        md += `**Severity:** ${v.severity.toUpperCase()} | `;
        md += `**Category:** ${v.category}\n\n`;
        
        if (v.source) {
          md += `**Source:** [${v.source}](${v.sourceUrl})\n\n`;
        }
        
        if (v.page) {
          md += `**Page:** \`${v.page}\`\n\n`;
        }
        
        md += `**Description:** ${v.description}\n\n`;
        md += `**Details:** ${v.details}\n\n`;
        md += `**Recommendation:** ${v.recommendation}\n\n`;
        
        if (v.impact) {
          md += `**Impact:** ${v.impact}\n\n`;
        }
        
        if (v.examples && v.examples.length > 0) {
          md += `**Examples:**\n`;
          v.examples.forEach(ex => {
            md += `- \`${ex}\`\n`;
          });
          md += `\n`;
        }
        
        md += `---\n\n`;
      });
    }
    
    md += `\n_Generated by Web Inspector_\n`;
    
    return md;
  }

  private generateHtml(result: WebAnalysisResult): string {
    const date = new Date(result.analyzedAt).toLocaleString();
    let scoreColor = '#f44336';
    if (result.overallScore >= 80) scoreColor = '#4caf50';
    else if (result.overallScore >= 60) scoreColor = '#ff9800';
    
    let html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Website Analysis Report - ${result.siteName}</title>
  <style>
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      line-height: 1.6;
      max-width: 1200px;
      margin: 0 auto;
      padding: 20px;
      background-color: #f5f5f5;
    }
    .header {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 30px;
      border-radius: 12px;
      margin-bottom: 20px;
    }
    .header h1 {
      margin: 0 0 10px 0;
    }
    .score {
      font-size: 48px;
      font-weight: bold;
      color: ${scoreColor};
    }
    .card {
      background: white;
      padding: 20px;
      margin-bottom: 20px;
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    .violation {
      border-left: 4px solid #ff9800;
      padding: 15px;
      margin-bottom: 15px;
      background: #fafafa;
      border-radius: 4px;
    }
    .severity {
      display: inline-block;
      padding: 4px 12px;
      border-radius: 4px;
      font-weight: bold;
      font-size: 12px;
      color: white;
    }
    .severity-error { background-color: #f44336; }
    .severity-warning { background-color: #ff9800; }
    .severity-info { background-color: #2196f3; }
    .source {
      background: #e8eaf6;
      padding: 8px 12px;
      border-radius: 6px;
      margin: 10px 0;
      border-left: 3px solid #667eea;
    }
    code {
      background: #e8eaf6;
      padding: 2px 6px;
      border-radius: 3px;
      color: #667eea;
    }
    table {
      width: 100%;
      border-collapse: collapse;
    }
    th, td {
      padding: 12px;
      text-align: left;
      border-bottom: 1px solid #ddd;
    }
    th {
      background-color: #667eea;
      color: white;
    }
    .footer {
      text-align: center;
      color: #666;
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #ddd;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>Website Analysis Report</h1>
    <h2>${result.siteName}</h2>
    <p>${result.siteUrl}</p>
    <p>Analyzed: ${date}</p>
    <div class="score">Score: ${result.overallScore}/100</div>
  </div>

  <div class="card">
    <h2>Summary</h2>
    <table>
      <tr><th>Metric</th><th>Count</th></tr>
      <tr><td>Total Rules Checked</td><td>${result.summary.totalRules}</td></tr>
      <tr><td>Passed</td><td>${result.summary.passedRules}</td></tr>
      <tr><td>Failed</td><td>${result.summary.failedRules}</td></tr>
      <tr><td>Warnings</td><td>${result.summary.warningRules}</td></tr>
    </table>
  </div>

  <div class="card">
    <h2>Issues and Violations</h2>`;

    if (result.violations && result.violations.length > 0) {
      result.violations.forEach((v, i) => {
        html += `
    <div class="violation">
      <h3>${i + 1}. ${v.ruleName}</h3>
      <span class="severity severity-${v.severity}">${v.severity.toUpperCase()}</span>
      <p><strong>Category:</strong> ${v.category}</p>`;
      
        if (v.source) {
          html += `<div class="source"><strong>Source:</strong> ${v.source}</div>`;
        }
        
        if (v.page) {
          html += `<p><strong>Page:</strong> <code>${v.page}</code></p>`;
        }
        
        html += `
      <p><strong>Description:</strong> ${v.description}</p>
      <p><strong>Details:</strong> ${v.details}</p>
      <p><strong>Recommendation:</strong> ${v.recommendation}</p>`;
      
        if (v.impact) {
          html += `<p><strong>Impact:</strong> ${v.impact}</p>`;
        }
      
        if (v.examples && v.examples.length > 0) {
          html += `<p><strong>Examples:</strong></p><ul>`;
          v.examples.forEach(ex => {
            html += `<li><code>${ex}</code></li>`;
          });
          html += `</ul>`;
        }
        
        html += `</div>`;
      });
    }

    html += `
  </div>

  <div class="footer">
    <p>Generated by Web Inspector</p>
    <p>${new Date().toISOString()}</p>
  </div>
</body>
</html>`;

    return html;
  }

  private generateCsv(result: WebAnalysisResult): string {
    let csv = 'Severity,Category,Rule Name,Page,Description,Details,Recommendation,Impact,Source\n';
    
    result.violations.forEach(v => {
      const row = [
        v.severity,
        v.category,
        v.ruleName,
        v.page || '',
        this.escapeCsv(v.description),
        this.escapeCsv(v.details),
        this.escapeCsv(v.recommendation),
        this.escapeCsv(v.impact || ''),
        v.source || ''
      ];
      csv += row.map(field => `"${field}"`).join(',') + '\n';
    });
    
    return csv;
  }

  private generateGitHubIssues(result: WebAnalysisResult): string {
    let issues = `# GitHub Issues for ${result.siteName}\n\n`;
    issues += `Copy and paste each section below as a new GitHub issue.\n\n`;
    issues += `---\n\n`;
    
    result.violations.filter(v => v.severity === 'error').forEach((v, i) => {
      issues += `## Issue ${i + 1}: ${v.ruleName}\n\n`;
      issues += `**Labels:** \`web-quality\`, \`${v.severity}\`, \`${v.category.toLowerCase().replace(/\s+/g, '-')}\`\n\n`;
      
      issues += `### Description\n${v.description}\n\n`;
      issues += `### Details\n${v.details}\n\n`;
      
      if (v.page) {
        issues += `### Affected Page\n\`${v.page}\`\n\n`;
      }
      
      issues += `### Recommendation\n${v.recommendation}\n\n`;
      
      if (v.impact) {
        issues += `### Impact\n${v.impact}\n\n`;
      }
      
      if (v.source) {
        issues += `### Authority Source\n[${v.source}](${v.sourceUrl})\n\n`;
      }
      
      if (v.examples && v.examples.length > 0) {
        issues += `### Examples\n`;
        v.examples.forEach(ex => issues += `- \`${ex}\`\n`);
        issues += `\n`;
      }
      
      issues += `---\n\n`;
    });
    
    return issues;
  }

  private generateJiraFormat(result: WebAnalysisResult): string {
    let jira = `JIRA Issues Import Format for ${result.siteName}\n`;
    jira += `${'='.repeat(60)}\n\n`;
    jira += `Copy each section and create as JIRA issue\n\n`;
    
    result.violations.filter(v => v.severity === 'error' || v.severity === 'warning').forEach((v, i) => {
      jira += `ISSUE ${i + 1}\n`;
      jira += `${'='.repeat(60)}\n`;
      jira += `Summary: [Web] ${v.ruleName}\n`;
      jira += `Issue Type: ${v.severity === 'error' ? 'Bug' : 'Improvement'}\n`;
      jira += `Priority: ${v.severity === 'error' ? 'High' : 'Medium'}\n`;
      jira += `Labels: web-quality, ${v.category.toLowerCase().replace(/\s+/g, '-')}\n\n`;
      
      jira += `Description:\n`;
      jira += `h3. Issue\n${v.description}\n\n`;
      jira += `h3. Details\n${v.details}\n\n`;
      
      if (v.page) {
        jira += `h3. Affected Page\n{code}${v.page}{code}\n\n`;
      }
      
      jira += `h3. Recommendation\n${v.recommendation}\n\n`;
      
      if (v.impact) {
        jira += `h3. Impact\n${v.impact}\n\n`;
      }
      
      if (v.source) {
        jira += `h3. Authority Source\n[${v.source}|${v.sourceUrl}]\n\n`;
      }
      
      if (v.examples && v.examples.length > 0) {
        jira += `h3. Examples\n`;
        v.examples.forEach(ex => jira += `* {{${ex}}}\n`);
        jira += `\n`;
      }
      
      jira += `\n${'='.repeat(60)}\n\n`;
    });
    
    return jira;
  }

  private escapeCsv(text: string): string {
    return text.replace(/"/g, '""');
  }

  private sanitizeFilename(name: string): string {
    return name.toLowerCase().replace(/[^a-z0-9]/g, '-').replace(/-+/g, '-');
  }

  private downloadFile(content: string, filename: string, mimeType: string): void {
    const blob = new Blob([content], { type: mimeType });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    link.click();
    window.URL.revokeObjectURL(url);
  }
}

